version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: pytech-test
    image: timescale/timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'pytech'
      POSTGRES_PASSWORD: 'pytech'
